name: EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "Solarcast-devops-ml" ]; then
              git clone https://github.com/${{ github.repository }}.git
            fi
            cd Solarcast-devops-ml
            git pull origin main
            sudo docker compose up -d --build
